#!/usr/bin/env bash
#Filename: testingForSymlinks
#From ABG on tldp.net
#written by Lee bigelow

[ $# -eq 0 ] && directorys=`pwd` || directorys=$@

linkchk () {
	for element in $1/*; do
	[ -h "$element" -a ! -e "$element" ] && echo \"$element\"
	[ -d "$element" ] && linkchk $element
	done
}

for directory in $directorys; do
	if [ -d $directory ]
		then linkchk $directory
		else
			echo "$directory is not a direcotry"
			echo "Usage: $0 dir1 dir2 ..."
	fi
done

exit $?

